stages:
    - mirror
    - prepare
    - build
    - deploy

mirror:
    stage: mirror
    tags: ["linux-docker-build"]
    image: alpine:3.13.1
    before_script:
        - apk update && apk add -q --no-cache bash git openssh
        - git config --global user.name "${GITLAB_USER_NAME}"
        - git config --global user.email "${GITLAB_USER_EMAIL}"
    script:
        - mkdir ~/.ssh
        - printf "%s\n" "${GITHUB_DEPLOY_KEY}" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        - git clone --bare ${CI_REPOSITORY_URL}
        - cd ${CI_PROJECT_NAME}.git
        - git push --mirror git@github.com:${GITHUB_REPO}.git

prepare:
    stage: prepare
    tags: ["windows-powershell-deploy"]
    rules:
       - if: '$CI_COMMIT_BRANCH == "master"'
    script:
        - powershell.exe -File ".\CI Scripts\dotnet-setup.ps1" -ExecutionPolicy Bypass

build:
    stage: build
    tags: ["linux-docker-build"]
    image: debian:buster-slim
    rules:
       - if: '$CI_COMMIT_BRANCH == "master"'
    script:
        - apt-get update && apt-get upgrade -y
        - apt-get install wget apt-transport-https zip -y
        - wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        - dpkg -i packages-microsoft-prod.deb
        - apt-get update && apt-get install -y dotnet-sdk-5.0
        - echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> /etc/environment && export DOTNET_CLI_TELEMETRY_OPTOUT=1
        - dotnet publish WASM.LibraryUtils --configuration Release --nologo --output PublishOutput
    artifacts:
        paths:
            - PublishOutput/*
        expire_in: 20 minutes

deploy:
    stage: deploy
    tags: ["windows-powershell-deploy"]
    rules:
       - if: '$CI_COMMIT_BRANCH == "master"'
    before_script:
        # Cleanup
        - $existingPool = Get-IISAppPool "${CI_PROJECT_TITLE}"
        - if(!$existingPool) { New-WebAppPool -Name "${CI_PROJECT_TITLE}" -Force }
        - $existingPool = Get-IISAppPool "${CI_PROJECT_TITLE}"
        - if($existingPool.State -ne "Stopped") { Stop-WebAppPool "${CI_PROJECT_TITLE}" }
        - Start-Sleep -Seconds 2
        - if (!(Test-Path -Path "${DEPLOY_PATH}")) { New-Item -ItemType directory -Path "${DEPLOY_PATH}" }
        - Get-ChildItem "${DEPLOY_PATH}" | Remove-Item -Recurse -Confirm:$false -Force
    script:
        - Expand-Archive "output.zip" -DestinationPath "${DEPLOY_PATH}"

        - $existingApp = Get-Website -Name "${CI_PROJECT_TITLE}"
        - Start-WebAppPool "${CI_PROJECT_TITLE}"
        - if (!$existingApp) { New-Website -Name "${CI_PROJECT_TITLE}" -PhysicalPath "${DEPLOY_PATH}" -ApplicationPool "${CI_PROJECT_TITLE}" -Force }

        - Start-WebSite -Name "${CI_PROJECT_TITLE}"
